### ISSUE TITLE
Receiving error Cannot find module 'jsonwebtoken@7.1.9' when using main-tenant-oidc

### ISSUE THREAD

**Issue by Yleisnero** [auth0-developer-hub/spa_angular_typescript_hello-world#2]
I have checked out the NestJS Code Sample for the backend and I want to use the Angular Code Sample for the frontend.

I am using:
Angular: 15.0.0
Node: 18.17.1
npm: 9.6.7
typescript: 4.8.4

In the package.json the sdk version looks like this: "@auth0/auth0-angular": "^2.0.0"

In the Auth0 Dashboard in the User Management I created a test user and I also have a active connection to my main-tenant where I do custom auth.
When I am logging in with my test user from the dashboard everything works fine. But when I try to use my main-tenant connection I get the following error in the callback:

Error: Cannot find module 'jsonwebtoken@7.1.9'
Require stack:
- /data/io/node18/affbf2df-8f85-4d8e-9a96-94f8c8e5c90c/webtask.js
    at auth0-spa-js.production.esm.js:1:30959
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    at asyncToGenerator.js:27:1
    at new ZoneAwarePromise (zone.js:1429:21)
    at asyncToGenerator.js:19:1
    at te.handleRedirectCallback (auth0-spa-js.production.esm.js:1:31338)
    at auth0-auth0-angular.mjs:440:45
    at Observable._subscribe (defer.js:5:19)

This error seems to occur somewhere in the AuthService module when calling the function handleRedirectCallback(url). 

Is there a way to fix this?

**Comment by Yleisnero** [comment]
Solution: 
The issue was that in my custom connection to the main tenant a script was specified to fetch the profile data including a wrong version number.
In the Auth0 Dashboard at Authentication -> Social -> <you-custom-connection> -> Settings there is a field called Fetch User Profile Script. In this script I had a require statement with a specify version. This version was not supported by the Node runtime of the Auth0 server anymore. I remove the version number to fix the issue.
